SERVER_PORT_GATEWAY: 8765

# эту настройку можно не выносить, если вы хотите,
# чтобы порт был закреплен за приложением, которое запускается
server:
  port: ${SERVER_PORT_GATEWAY}
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          # Настроить шлюз для создания маршрутов на основе services,
          # зарегистрированных в DiscoveryClient, в реестре совместимых служб.
          # Включить данную возможность
          enabled: true
          # имена сервисов будут принудительно переведены в нижний регистр
          # (это необходимое условие, чтобы Gateway, мог зарегистрировать их у себя)
          # если информация в информации о зарегистрированном сервисе,
          # id сервиса будет заглавными буквами
          lower-case-service-id: true
      routes:
        # уникальный id описываемого маршрута
        # с помощью данного id, можно работать также с этим маршрутом
        - id: info-application-eureka-client-info
          # указываем uri endpoint, на который нужно перенаправить запрос
          # также указываем тип http-метода, которым этот запрос должен быть обработан
          predicates:
            - Path=/api/info
            - Method=GET
          # Указываем имя сервиса, на который должен быть перенаправлен данный запрос.
          # 'lb' - означает load balancer, так как Api gateway будет балансировать нагрузку
          # если при горизонтальном масштабировании, будет несколько реплик сервиса - eureka-client.yml
          uri: lb://eureka-client
        # уникальный id описываемого маршрута
        # с помощью данного id, можно работать также с этим маршрутом
        - id: info-application-eureka-client-id
          # указываем uri endpoint, на который нужно перенаправить запрос
          # также указываем тип http-метода, которым этот запрос должен быть обработан
          predicates:
            - Path=/api/id
            - Method=GET
          # Указываем имя сервиса, на который должен быть перенаправлен данный запрос.
          # 'lb' - означает load balancer, так как Api gateway будет балансировать нагрузку
          # если при горизонтальном масштабировании, будет несколько реплик сервиса - eureka-client.yml
          uri: lb://eureka-client
        - id: info-application-eureka-client-copy
          predicates:
            - Path=/api/id-second-service
            - Method=GET
          uri: lb://eureka-client-second-copy