SERVER_PORT_SERVICE_DISCOVERY: 8761
IP_ADDRESS_SERVICE_DISCOVERY: http://localhost

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  # https://docs.spring.io/spring-cloud-netflix/docs/current/reference/html/#changing-the-eureka-instance-id
  service-url:
    #Адрес сервера регистрации(eureka-server.yml)
    defaultZone: http://localhost:8761/eureka